############################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-host
  labels:
    app: flask-host
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-host
  template:
    metadata:
      labels:
        app: flask-host
    spec:
      containers:
      - name: flask-host
        image: jenkins-docker:5000/flask-host:build-{{BUILD_NUMBER}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-number
  labels:
    app: flask-number
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-number
  template:
    metadata:
      labels:
        app: flask-number
    spec:
      containers:
      - name: flask-number
        image: jenkins-docker:5000/flask-number:build-{{BUILD_NUMBER}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-letter
  labels:
    app: flask-letter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-letter
  template:
    metadata:
      labels:
        app: flask-letter
    spec:
      containers:
      - name: flask-letter
        image: jenkins-docker:5000/flask-letter:build-{{BUILD_NUMBER}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-sequence
  labels:
    app: flask-sequence
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-sequence
  template:
    metadata:
      labels:
        app: flask-sequence
    spec:
      containers:
      - name: flask-sequence
        image: jenkins-docker:5000/flask-sequence:build-{{BUILD_NUMBER}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-prize
  labels:
    app: flask-prize
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-prize
  template:
    metadata:
      labels:
        app: flask-prize
    spec:
      containers:
      - name: flask-number
        image: jenkins-docker:5000/flask-prize:build-{{BUILD_NUMBER}}
---
apiVersion: v1
kind: Service
metadata:
  name: flask-host
spec:
  selector:
    app: flask-host
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
 name: flask-number
spec:
 ports:
 - protocol: TCP
   port: 5000
   targetPort: 5000
 selector:
   app: flask-number
 type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
 name: flask-letter
spec:
 ports:
 - protocol: TCP
   port: 5000
   targetPort: 5000
 selector:
   app: flask-letter
 type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
 name: flask-sequence
spec:
 ports:
 - protocol: TCP
   port: 5000
   targetPort: 5000
 selector:
   app: flask-sequence
 type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
 name: flask-prize
spec:
 ports:
 - protocol: TCP
   port: 5000
   targetPort: 5000
 selector:
   app: flask-prize
 type: ClusterIP
