apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: jenkins-home
spec:
 accessModes:
 - ReadWriteOnce
 resources:
  requests:
   storage: 10Gi

---
apiVersion: v1
kind: Pod
metadata:
 name: jenkins
 labels:
  app: jenkins
spec:
 securityContext: 
  fsGroup: 1000
 containers:
 - name: jenkins
   securityContext: 
    runAsUser: 1000
   image: jenkins/jenkins:lts-alpine
   ports:
   - containerPort: 8080
   volumeMounts: 
   - mountPath: "/var/jenkins_home"
     name: jenkins-home 
 volumes:
 - name: jenkins-home
   persistentVolumeClaim:
    claimName: jenkins-home

---
apiVersion: v1
kind: Service
metadata:
 name: jenkins
spec:
 selector:
  app: jenkins
 ports: 
 - protocol: TCP
   port: 80
   targetPort: 8080
 type: LoadBalancer

---
apiVersion: v1
kind: Pod
metadata:
  name: registry
  labels:
    app: registry
spec:
 containers:
 - name: registry
   image: registry:2
---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  selector:
    app: registry
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
